### ISSUE TITLE
CFD displays dates outside of selected date range

### ISSUE THREAD

**Issue by satvidh** [paulsjv/leansheets#13]
See the attached image below.

![image](https://cloud.githubusercontent.com/assets/8485120/7669050/68fa2b52-fc23-11e4-998e-13bc9a82c6ce.png)

Here is the config.json. 

{
    "dataUrl": "https://docs.google.com/a/google.com/spreadsheet/ccc?key=1-oqW-ydivjh8Q8cJkRtKEjC5vWda8k-2SKvcf039NS8&gid=1875287028",
    "configUrl": "https://docs.google.com/a/google.com/spreadsheet/ccc?key=1-oqW-ydivjh8Q8cJkRtKEjC5vWda8k-2SKvcf039NS8&gid=1843000943",
    "debugEnabled": true,
    "showAllWork": true,
    "cacheTtl": 300,
    "datePickerFormat": "mm/dd/yyyy",
    "datePickerMomentFormat": "MM/DD/YYYY",
    "queryDateMomentFormat": "YYYY-MM-DD",
    "defaultHistoricalNumberOfDays": 60
}

**Comment by paulsjv** [comment]
Thanks for the catch.  I'll try to take a look at it this weekend and get a resolution to it as well.

**Comment by paulsjv** [comment]
Here are the 2 queries that are being run to get the data for the CFD chart:

```
cfdStartQuery = "select C, count(A) where %t C is not null AND toDate(C) >= toDate(date '%sd') AND toDate(C) <= toDate(date '%ed') group by C",
cfdEndQuery = "select D, count(A) where %t D is not null AND toDate(C) >= toDate(date '%sd') AND toDate(C) <= toDate(date '%ed') group by D",
```

Note - that C is the "Start Date" and D is the "End Date"

Take a look at the ls-cfdService.js algorithm to see how it takes these 2 data sets and merges them together to get the final CFD chart.  I suspect the logic in there is a cause for why there is a date range issue.

**Comment by paulsjv** [comment]
Taking a closer look at the issue and I believe there is an issue when counting the WIP for a day in the algorithm.  Once the build framework work is complete need to add a unit test so that this issue can get resolved easier.

**Comment by SandipNirmal** [comment]
After debugging the code i found following.

cfdEndQuery value should be  

"select D, count(A) where %t D is not null AND toDate(D) >= toDate(date '%sd') AND toDate(D) <= toDate(date '%ed') group by D",

instead of 

cfdEndQuery = "select D, count(A) where %t D is not null AND toDate(C) >= toDate(date '%sd') AND toDate(D) <= toDate(date '%ed') group by D",

We need end date, we are comparing against wrong column.

![screenshot from 2015-11-16 17 20 59](https://cloud.githubusercontent.com/assets/5370460/11181282/ea550d9a-8c86-11e5-8483-04efaf3c4aa0.png)

**Comment by paulsjv** [comment]
Issue fixed with this [commit](https://github.com/paulsjv/leansheets/commit/421cbeb6bd7e8d3e47e073244e92acee6f472fbf).
