### ISSUE TITLE
Bug: CFD does not display when user changes date range

### ISSUE THREAD

**Issue by satvidh** [paulsjv/leansheets#29]
Notice the 2 images below that show the Lead Time Histogram and the CFD respectively. Both of the images show the date range from 8/1/2015 to 2/1/2016. The Lead Time Histogram displays the correct data, while the CFD is blank.

![image](https://cloud.githubusercontent.com/assets/8485120/12700791/8ed33152-c7b6-11e5-8c08-bdea93f7833e.png)

![image](https://cloud.githubusercontent.com/assets/8485120/12700789/6ea196bc-c7b6-11e5-9ed3-394631717b15.png)

**Comment by paulsjv** [comment]
Thanks for reporting the bug.  This issue is known.  With the current released version this bug is not going to be fixed due to the work being done on the 2.0 branch.  There will be a new CFD released with that version that has more functionality with more information.  

Workaround is to select a smaller data set and the CFD should render.
